snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://%redis_host%'
            logging: '%kernel.debug%'
        session:
            type: 'predis'
            alias: 'session'
            dsn: 'redis://%redis_host%'
            logging: true
        cache:
            type: predis
            alias: cache
            dsn: 'redis://%redis_host%'
            logging: true
    session:
        client: session
        prefix: session_
        ttl: 3600
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
            document_manager: default
        result_cache:
           client: cache
           entity_manager: [default, read]
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default
